from __future__ import annotations

import asyncio
import base64
from dataclasses import dataclass
from datetime import datetime
from html import escape
from io import BytesIO
from pathlib import Path
from string import Template

import structlog
from PIL import Image
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.utils import ImageReader
from reportlab.pdfgen import canvas

from app.config import Settings
from app.models.case import CaseRecord
from app.models.result import CaseResult
from app.services.inference.preprocess import load_source_image_bytes
from app.services.storage.base import StorageBackend

logger = structlog.get_logger(__name__)

REPORT_DISCLAIMER = (
    "DISCLAIMER: This report is generated by an AI clinical decision-support system and is intended to "
    "assist, not replace, the clinical judgment of a qualified ophthalmologist. All clinical decisions "
    "remain the sole responsibility of the treating physician. This tool has not been approved as a "
    "standalone diagnostic device. For research and screening support purposes only."
)

CHANNEL_LABELS = {
    "ma": "Microaneurysms",
    "he": "Hard Exudates",
    "hem": "Haemorrhages",
    "se": "Soft Exudates",
    "irma": "IRMA",
    "nv": "Neovascularisation",
}

REFERRAL_STYLES = {
    "none": {"class_name": "referral-safe", "title": "NO REFERRAL REQUIRED"},
    "routine": {"class_name": "referral-routine", "title": "REFER TO OPHTHALMOLOGIST"},
    "urgent": {"class_name": "referral-urgent", "title": "REFER TO OPHTHALMOLOGIST"},
    "emergency": {"class_name": "referral-emergency", "title": "REFER TO OPHTHALMOLOGIST"},
}

TEMPLATE_DIR = Path(__file__).resolve().parent / "templates"


@dataclass(slots=True)
class ReportAssets:
    original_image_uri: str | None
    composite_image_uri: str | None


class PDFReportGenerator:
    def __init__(self, settings: Settings, storage: StorageBackend) -> None:
        self.settings = settings
        self.storage = storage
        self.html_template = Template((TEMPLATE_DIR / "report.html").read_text(encoding="utf-8"))
        self.css_template = (TEMPLATE_DIR / "report.css").read_text(encoding="utf-8")

    async def generate_case_report(self, *, case: CaseRecord, result: CaseResult) -> bytes:
        return await asyncio.to_thread(self._render_report, case, result)

    def _render_report(self, case: CaseRecord, result: CaseResult) -> bytes:
        html_document = self._build_html(case, result)

        try:
            from weasyprint import CSS, HTML
        except (ImportError, OSError) as exc:
            logger.warning("weasyprint_unavailable_falling_back_to_reportlab", detail=str(exc))
            return self._render_reportlab_fallback(case, result)

        return HTML(
            string=html_document,
            base_url=str(TEMPLATE_DIR),
        ).write_pdf(stylesheets=[CSS(string=self.css_template)])

    def _build_html(self, case: CaseRecord, result: CaseResult) -> str:
        report_assets = self._build_report_assets(case, result)
        referral_style = REFERRAL_STYLES[result.referral_urgency]

        original_figure = self._build_figure_block(
            title="Original fundus image",
            image_uri=report_assets.original_image_uri,
            fallback_message="Preview unavailable for this file format.",
        )
        overlay_figure = self._build_figure_block(
            title="Composite lesion overlay",
            image_uri=report_assets.composite_image_uri,
            fallback_message="Overlay preview unavailable.",
        )
        notes_section = self._build_notes_section(case.notes)
        lesion_rows = self._build_lesion_rows(result)

        return self.html_template.safe_substitute(
            logo_data_uri=self._build_logo_data_uri(),
            patient_ref=escape(case.patient_ref),
            case_id=escape(case.id),
            eye_side=escape(case.eye_side.title()),
            case_datetime=escape(self._format_datetime(case.created_at)),
            operator_name=escape(self._get_operator_name(case)),
            referral_class=referral_style["class_name"],
            referral_decision=escape(referral_style["title"]),
            referral_label=escape(result.referral_label),
            grade_display=escape(f"Grade {result.grade} — {result.grade_label}"),
            confidence_tier=escape(f"{result.confidence_tier.title()} confidence"),
            confidence_explanation=escape(result.confidence_explanation),
            clinical_summary=escape(result.clinical_summary),
            original_figure=original_figure,
            overlay_figure=overlay_figure,
            lesion_rows=lesion_rows,
            notes_section=notes_section,
            model_version=escape(result.model_version),
            processed_at=escape(self._format_datetime(result.processed_at)),
            report_footer_date=escape(self._format_footer_date(result.processed_at)),
            disclaimer_text=escape(REPORT_DISCLAIMER),
        )

    def _build_report_assets(self, case: CaseRecord, result: CaseResult) -> ReportAssets:
        original_image = self._load_original_image(case)
        original_uri = self._image_to_data_uri(original_image) if original_image is not None else None
        composite_uri = self._image_to_data_uri(self._build_composite_overlay(original_image, result))
        return ReportAssets(original_image_uri=original_uri, composite_image_uri=composite_uri)

    def _load_original_image(self, case: CaseRecord) -> Image.Image | None:
        if not (case.image_content_type.startswith("image/") or case.image_content_type == "application/dicom"):
            return None

        try:
            payload = asyncio.run(self.storage.read_bytes(case.image_storage_path))
            image = load_source_image_bytes(
                payload=payload,
                content_type=case.image_content_type,
                filename=case.image_original_filename,
            )
            return image.convert("RGBA")
        except Exception:
            return None

    def _build_composite_overlay(self, original_image: Image.Image | None, result: CaseResult) -> Image.Image | None:
        if original_image is None:
            return None

        composite = original_image.copy()
        for channel in CHANNEL_LABELS:
            if not result.lesion_presence.get(channel):
                continue
            overlay_relative_path = result.overlay_paths.get(channel)
            if not overlay_relative_path:
                continue

            try:
                overlay_payload = asyncio.run(self.storage.read_bytes(overlay_relative_path))
            except Exception:
                continue

            with Image.open(BytesIO(overlay_payload)) as overlay_image:
                prepared_overlay = overlay_image.convert("RGBA")
                if prepared_overlay.size != composite.size:
                    prepared_overlay = prepared_overlay.resize(composite.size, resample=Image.BICUBIC)
                composite = Image.alpha_composite(composite, prepared_overlay)

        return composite

    def _image_to_data_uri(self, image: Image.Image | None) -> str | None:
        if image is None:
            return None

        buffer = BytesIO()
        image.save(buffer, format="PNG")
        encoded = base64.b64encode(buffer.getvalue()).decode("ascii")
        return f"data:image/png;base64,{encoded}"

    def _build_figure_block(self, *, title: str, image_uri: str | None, fallback_message: str) -> str:
        content = (
            f'<img src="{image_uri}" alt="{escape(title)}" />'
            if image_uri is not None
            else f'<div class="figure-placeholder">{escape(fallback_message)}</div>'
        )
        return (
            '<div class="figure-card">'
            f'<p class="figure-title">{escape(title)}</p>'
            f"{content}"
            "</div>"
        )

    def _build_lesion_rows(self, result: CaseResult) -> str:
        rows: list[str] = []
        for channel, label in CHANNEL_LABELS.items():
            detected = "Yes" if result.lesion_presence.get(channel, False) else "No"
            rows.append(
                "<tr>"
                f"<td>{escape(label)}</td>"
                f'<td class="detected-{detected.lower()}">{detected}</td>'
                "</tr>"
            )
        return "".join(rows)

    def _build_notes_section(self, notes: str | None) -> str:
        if not notes:
            return ""

        return (
            '<section class="section notes-section">'
            '<h2>Clinical notes</h2>'
            f"<p>{escape(notes)}</p>"
            "</section>"
        )

    def _get_operator_name(self, case: CaseRecord) -> str:
        if getattr(case, "user", None) is not None and case.user.full_name:
            return case.user.full_name
        return "Visara Operator"

    def _format_datetime(self, value: datetime) -> str:
        formatted = value.strftime("%d %b %Y, %H:%M %Z")
        return formatted.strip() or value.isoformat()

    def _format_footer_date(self, value: datetime) -> str:
        return value.strftime("%d %b %Y")

    def _build_logo_data_uri(self) -> str:
        svg = """
<svg xmlns="http://www.w3.org/2000/svg" width="120" height="40" viewBox="0 0 120 40" fill="none">
  <rect width="40" height="40" rx="12" fill="#0F1629"/>
  <path d="M20 10C12.8 10 7.2 16 5 20C7.2 24 12.8 30 20 30C27.2 30 32.8 24 35 20C32.8 16 27.2 10 20 10Z" fill="#0EA5E9"/>
  <circle cx="20" cy="20" r="5.5" fill="#FFFFFF"/>
  <path d="M56 15.5H59.6L65.8 29H62.6L61.3 26H54.1L52.8 29H49.6L56 15.5ZM55.2 23.7H60.2L57.7 18L55.2 23.7Z" fill="#0F1629"/>
  <path d="M67.9 15.5H78.6V18.1H70.9V21H77.6V23.5H70.9V29H67.9V15.5Z" fill="#0F1629"/>
  <path d="M80.2 15.5H90.9V18.1H83.2V20.8H89.9V23.3H83.2V26.4H91V29H80.2V15.5Z" fill="#0F1629"/>
  <path d="M92.9 15.5H96L101.9 24.1V15.5H104.9V29H101.9L95.9 20.4V29H92.9V15.5Z" fill="#0F1629"/>
  <path d="M107.2 15.5H112.7C116.8 15.5 119.3 18 119.3 22.2C119.3 26.5 116.8 29 112.7 29H107.2V15.5ZM110.2 18.1V26.4H112.6C114.9 26.4 116.2 24.9 116.2 22.2C116.2 19.6 114.9 18.1 112.6 18.1H110.2Z" fill="#0F1629"/>
</svg>
""".strip()
        encoded = base64.b64encode(svg.encode("utf-8")).decode("ascii")
        return f"data:image/svg+xml;base64,{encoded}"

    def _render_reportlab_fallback(self, case: CaseRecord, result: CaseResult) -> bytes:
        buffer = BytesIO()
        pdf = canvas.Canvas(buffer, pagesize=A4)
        width, height = A4

        referral_style = REFERRAL_STYLES[result.referral_urgency]
        fallback_colors = {
            "referral-safe": "#22C55E",
            "referral-routine": "#F59E0B",
            "referral-urgent": "#F97316",
            "referral-emergency": "#EF4444",
        }

        pdf.setTitle(f"Visara Report - {case.id}")
        pdf.setFillColor(colors.HexColor("#0F1629"))
        pdf.rect(0, height - 80, width, 80, fill=1, stroke=0)
        pdf.setFillColor(colors.white)
        pdf.setFont("Helvetica-Bold", 18)
        pdf.drawString(36, height - 42, "Visara")
        pdf.setFont("Helvetica", 11)
        pdf.drawRightString(width - 36, height - 42, "AI-Assisted DR Screening Report")

        current_y = height - 118
        pdf.setFillColor(colors.HexColor("#0F1629"))
        pdf.setFont("Helvetica", 10)
        pdf.drawString(36, current_y, f"Patient Reference: {case.patient_ref}")
        pdf.drawRightString(width - 36, current_y, f"Case ID: {case.id}")
        current_y -= 16
        pdf.drawString(36, current_y, f"Eye: {case.eye_side.title()}")
        pdf.drawRightString(width - 36, current_y, f"Date & Time: {self._format_datetime(case.created_at)}")
        current_y -= 16
        pdf.drawString(36, current_y, f"Referring operator: {self._get_operator_name(case)}")

        current_y -= 38
        pdf.setFillColor(colors.HexColor(fallback_colors[referral_style["class_name"]]))
        pdf.roundRect(36, current_y - 50, width - 72, 52, 10, fill=1, stroke=0)
        pdf.setFillColor(colors.white)
        pdf.setFont("Helvetica-Bold", 16)
        pdf.drawString(50, current_y - 20, referral_style["title"])
        pdf.setFont("Helvetica", 10)
        pdf.drawString(50, current_y - 36, result.referral_label)

        current_y -= 78
        pdf.setFillColor(colors.HexColor("#0F1629"))
        pdf.setFont("Helvetica-Bold", 11)
        pdf.drawString(36, current_y, "Findings summary")
        pdf.setFont("Helvetica", 10)
        pdf.drawString(36, current_y - 16, f"DR Grade: Grade {result.grade} — {result.grade_label}")
        pdf.drawString(36, current_y - 32, f"Confidence: {result.confidence_tier.title()} confidence")
        pdf.drawString(36, current_y - 48, result.confidence_explanation[:120])

        assets = self._build_report_assets(case, result)
        if assets.original_image_uri:
            with Image.open(BytesIO(base64.b64decode(assets.original_image_uri.split(",", 1)[1]))) as original_image:
                pdf.drawImage(ImageReader(original_image), 36, current_y - 210, width=220, height=160, preserveAspectRatio=True)
        if assets.composite_image_uri:
            with Image.open(BytesIO(base64.b64decode(assets.composite_image_uri.split(",", 1)[1]))) as overlay_image:
                pdf.drawImage(
                    ImageReader(overlay_image),
                    width - 256,
                    current_y - 210,
                    width=220,
                    height=160,
                    preserveAspectRatio=True,
                )
        pdf.setFont("Helvetica", 9)
        pdf.drawString(36, current_y - 222, "Left: Original fundus image. Right: AI-detected lesion overlay.")

        table_y = current_y - 258
        pdf.setFont("Helvetica-Bold", 11)
        pdf.drawString(36, table_y, "Lesion findings")
        pdf.setFont("Helvetica", 10)
        row_y = table_y - 18
        for channel, label in CHANNEL_LABELS.items():
            pdf.drawString(36, row_y, label)
            pdf.drawRightString(width - 36, row_y, "Yes" if result.lesion_presence.get(channel) else "No")
            row_y -= 14

        if case.notes:
            row_y -= 8
            pdf.setFont("Helvetica-Bold", 11)
            pdf.drawString(36, row_y, "Clinical notes")
            pdf.setFont("Helvetica", 10)
            pdf.drawString(36, row_y - 16, case.notes[:220])
            row_y -= 34

        row_y -= 6
        pdf.setFont("Helvetica-Bold", 11)
        pdf.drawString(36, row_y, "Model information")
        pdf.setFont("Helvetica", 10)
        pdf.drawString(36, row_y - 16, f"Model: {result.model_version}")
        pdf.drawString(36, row_y - 32, "Architecture: Dual-encoder (RETFound ViT-L + SAM ViT-H)")
        pdf.drawString(36, row_y - 48, "Validation performance: QWK 0.853, RefAUC 0.926 (FGADR benchmark)")
        pdf.drawString(36, row_y - 64, "Training institution: BITS Pilani")

        pdf.setStrokeColor(colors.HexColor("#CBD5E1"))
        pdf.line(36, 62, width - 36, 62)
        pdf.setFont("Helvetica", 8)
        pdf.setFillColor(colors.HexColor("#334155"))
        pdf.drawString(36, 48, REPORT_DISCLAIMER[:145])
        pdf.drawString(36, 36, REPORT_DISCLAIMER[145:290])
        pdf.drawString(36, 24, f"Visara | BITS Pilani Research | {self._format_footer_date(result.processed_at)}")

        pdf.save()
        buffer.seek(0)
        return buffer.getvalue()
